spring.application.name=gaming-platform
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
app.jwtSecret="your-very-long-secret-key-at-least-32-characters-for-hs512"
app.jwtExpirationMs=86400000
spring.resources.static-locations=classpath:/public/,file:/var/www/html/
spring.resources.cache.period=-1
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB